name: Integrate $(Date:yyyyMMdd).$(Rev:.r)
variables:
  - template: variables/vars.yml
  - name: BUILDSECMON_OPT_IN
    value: true
    
pr: none
trigger:
  branches:
    include:
      - main
      - '*-stable'
  paths:
    exclude:
      - '*.md'

jobs:
  - template: apple-integration-jobs.yml
